# Generated by Django 4.1.9 on 2023-05-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="innovatemodel",
            name="email",
            field=models.CharField(default="", max_length=150),
        ),
    ]
